import { Toaster } from "sonner";

import type { Metadata } from "next";

import Navbar from "@/components/Shared/Navbar/Navbar";
import WrapperMaxWidth from "@/components/Shared/WrapperMaxWidth";
import Footer from "@/components/Shared/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Navbar />
      <main className="min-h-screen mt-6 lg:mt-12">
        <WrapperMaxWidth>
          {children}
        </WrapperMaxWidth>
      </main>
      <Footer />
      <Toaster />
    </>
  );
}
