import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import WrapperMaxWidth from "@/components/WrapperMaxWidth";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Navbar />
      <main className=" mt-6 lg:mt-12">
        <WrapperMaxWidth>
          {children}
        </WrapperMaxWidth>
      </main>
      <Toaster />
    </>
  );
}
